services:
  # --- 1. DATABASE (POSTGRESQL) ---
  db:
    image: postgres:15
    container_name: resume-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resumedb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d resumedb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- 2. AI SERVICE (PYTHON) ---
  ai-service:
    build: ./ai-service  # Pastikan nama folder ni betul
    container_name: ai-service
    ports:
      - "8000:8000"
    restart: always

  # --- 3. BACKEND SERVICE (JAVA) ---
  backend-service:
    build: ./backend-service # Pastikan nama folder ni betul
    container_name: backend-service
    ports:
      - "8080:8080"
    environment:
      # Kita override application.properties guna ni:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/resumedb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      AI_SERVICE_URL: http://ai-service:8000/classify
    depends_on:
      db:
        condition: service_healthy
      ai-service:
        condition: service_started