spring.application.name=resumebackend

# Set the max file size (e.g., 10MB)
spring.servlet.multipart.max-file-size=10MB
# Set the max total request size (e.g., 10MB)
spring.servlet.multipart.max-request-size=10MB